env:
  node: true
extends:
  - 'prettier'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  curly: ['error', 'multi-line']
  indent: 'off'
